### ISSUE TITLE
[BUG] F8 Hotkey not working in version 3.5

### ISSUE THREAD

**Issue by james-berkheimer** [ApacheTech-VintageStory-Mods/AccessibilityTweaks#1]
VS version 1.19.3
Mod version 3.5

When I hit the F8 key nothing happens.  I don't see the any entry for it in the Controls page of the Settings.

**Comment by ApacheTech** [comment]
I'll need copies of your client-side log files. `client-main.txt`, and `client-debug.txt`.

**Comment by james-berkheimer** [comment]
> I'll need copies of your client-side log files. `client-main.txt`, and `client-debug.txt`.
> 
> Make sure the mod is installed, and enabled. Log into a world. If it doesn't work, log out, close the game, then upload your log files to here.
> 
> If you open the game again, it will overwrite the log files, and you'll have to do it all again.

Sorry about that.  Kind of created the issue in a hurry.  I'm away and won't be able to play the game for a few days.  Once I return home I'll get the logs for you.
