### ISSUE TITLE
Unable to turn off sound effects in 1.19.6

### ISSUE THREAD

**Issue by james-berkheimer** [ApacheTech-VintageStory-Mods/AccessibilityTweaks#2]
I just updated to 1.19.6 this morning and noticed that the sound effects I turned off are now still playing.  The settings still show them turned off however.

![image](https://github.com/ApacheTech-VintageStory-Mods/AccessibilityTweaks/assets/5049386/39099922-17e9-4185-876a-a9aa8eadb90b)

![image](https://github.com/ApacheTech-VintageStory-Mods/AccessibilityTweaks/assets/5049386/381d3d21-ddd8-4099-b7c7-b0c217b69b9a)

**Comment by james-berkheimer** [comment]
Please let me know what other data you need to debug this.  I looked through the client logs and didn't see anything that jumped out as an error for this mod.

**Comment by ApacheTech** [comment]
Has this been fixed in 3.6.2?

If not, I'll need your log files (client-main, and client-debug). I can't reproduce this within the latest version, so it may have already been fixed.

**Comment by james-berkheimer** [comment]
I reverted back to 1.19.5 because I was having other issues with that release.  I'll version up to 1.19.7 and test your latest release later today and let you know if the issue I had persists.

**Comment by ApacheTech** [comment]
Ok. 1.19.6 definitely did break this mod version 3.6.1, due to changes with chat text alteration when drunk. It broke the Harmony patches in my mod, and when one breaks, they all break. But I did fix that problem with 3.6.2, which was released a couple of days ago.

**Comment by james-berkheimer** [comment]
Oh OK, then I'll close this issue.  If I do have the same issue I'll just let you know.
