### ISSUE TITLE
[BUG] 1.19.5: Temporal Storm Perception Warp Never Goes Away

### ISSUE THREAD

**Issue by VaelophisNyx** [ApacheTech-VintageStory-Mods/AccessibilityTweaks#3]
**Describe the Bug:**
After a temporal storm the world remains wavy and warped permanently until the Perception Warp setting in Camera Movement is set to 0%
It resume if taken back above 0%

**To Reproduce:**
Set Perception Warp to anything above 100%
Experience a temporal storm (`/nexttempstorm now`)
the effect does not go away
set it to 0%
the effect is solved

**Expected Behaviour:**
the effect should clear automatically at the end of the storm

**Comment by ApacheTech** [comment]
Hi, I've released 3.7.0, which should solve this. I've removed the entire Glitch Strength feature, as it's now covered by the base game. If the issues still exist, please re-open this ticket, and I'll check the perception warp strength.
