### ISSUE TITLE
[BUG] Absolute Drunkenness 

### ISSUE THREAD

**Issue by melodelic** [ApacheTech-VintageStory-Mods/AccessibilityTweaks#5]
**Describe the Bug:**
After I died on my most recent save a few days ago, every save I had was drunk. Even on new saves not related to anything else, I was drunk if I had AccessibilityTweaks on. If I turned it off, it instantly went away. If I did .debug perceptioneffect drunk 0 , it would stop until I died or reloaded the world and then the drunkenness would come back. I have absolutely no clue why this suddenly happened.

**To Reproduce:**
Steps to reproduce the behaviour:
¯\_(ツ)_/¯ 

**Expected Behaviour:**
The world just looks completely drunk with AccessibilityTweaks on. The slider for Perception Warp Strength does nothing. The only thing that stops the drunkenness is to either do the .debug or turn it off via the mod menu. The video below shows the issue as well as me turning it on and off via the mod menu.

https://youtu.be/-V7je--q2VU 

**Additional Context**
client.main: https://gist.github.com/melodelic/44b5643ac85c5dee0a16fc4c206810c3
server.main: https://gist.github.com/melodelic/1c6ac1dfe2c16a3fd574f921b2c217fe

**Comment by ApacheTech** [comment]
I've tried a new way of controlling the drunk effect. I'm not controlling the shader directly now. I'm hoping this will be better. This has been a problem for a while.

(Hopefully) fixed within 3.7.1

**Comment by melodelic** [comment]
Ah! It works again! Thank you so much for getting this new patch out! <3
